apiVersion: v1
kind: Service
metadata:
  name: nats-metrics
  namespace: nats
  labels:
    app.kubernetes.io/name: nats
    app: nats-metrics
spec:
  ports:
  - name: metrics
    port: 7777
    targetPort: 7777
    protocol: TCP
  selector:
    app.kubernetes.io/name: nats   # Этот селектор найдет твои поды nats-0, nats-1...
  type: ClusterIP