# ============================================================================
# Nexus 3 с разделением хранилищ (ИСПРАВЛЕННЫЙ v2)
# БД (OrientDB) → Longhorn | Блобы → MinIO S3
# Проблема: ConfigMap не должен мешать писать в /nexus-data/etc
# ============================================================================

---
# 1. Создаём Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: nexus


---
# 2a. PVC для БД (Longhorn, SSD)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-db
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi


---
# 2b. Small PVC для конфигов и логов
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-config
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi


---
# 3. Основное приложение (Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      # Init-контейнер для инициализации директорий
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command: 
            - sh
            - -c
            - |
              mkdir -p /nexus-data/blobs
              mkdir -p /nexus-data/db
              mkdir -p /nexus-data/log
              mkdir -p /nexus-data/tmp
              mkdir -p /nexus-data/etc
              mkdir -p /nexus-config
              chown -R 200:200 /nexus-data /nexus-config
              chmod -R 755 /nexus-data /nexus-config
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: nexus-db
              mountPath: /nexus-data
            - name: nexus-config
              mountPath: /nexus-config

      containers:
        - name: nexus
          image: sonatype/nexus3:3.70.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 200
            runAsGroup: 200
          ports:
            - containerPort: 8081
              name: ui
            - containerPort: 8082
              name: docker-hosted
          
          # Переменные окружения для Java и Nexus
          env:
            - name: NEXUS_CONTEXT
              value: "/"
            - name: INSTALL4J_ADD_VM_PARAMS
              value: >
                -Xms1g
                -Xmx2g
                -XX:+UseG1GC
                -XX:MaxGCPauseMillis=50
                -XX:+ParallelRefProcEnabled
          
          # Подмонтировать тома (БЕЗ ConfigMap!)
          volumeMounts:
            - name: nexus-db
              mountPath: /nexus-data
            - name: nexus-config
              mountPath: /nexus-config
          
          # Ресурсы
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "2000m"
          
          # Пробы живучести (Nexus долго стартует)
          livenessProbe:
            httpGet:
              path: /service/rest/v1/status
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 6
            timeoutSeconds: 5
          
          readinessProbe:
            httpGet:
              path: /service/rest/v1/status
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 6
            timeoutSeconds: 5

      volumes:
        - name: nexus-db
          persistentVolumeClaim:
            claimName: nexus-db
        - name: nexus-config
          persistentVolumeClaim:
            claimName: nexus-config


---
# 4. Service
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  type: ClusterIP
  ports:
    - name: ui
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: docker
      port: 8082
      targetPort: 8082
      protocol: TCP


---
# 5. Ingress (Маршрутизация)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: nexus
  annotations:
    # Критически важные настройки для Docker Registry
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    # Отключить request body checking (для больших образов)
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - registry-nexus.ccsfarm.local
        - nexus.ccsfarm.local
      secretName: nexus-tls-secret
  rules:
    # Хост для UI админки
    - host: nexus.ccsfarm.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus-service
                port:
                  number: 8081
    # Хост для команд docker push/pull
    - host: registry-nexus.ccsfarm.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus-service
                port:
                  number: 8082
