apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "admin"
  AWS_SECRET_ACCESS_KEY: "password"
  # Важно: указываем внутренний адрес, так как Longhorn внутри кластера
  AWS_ENDPOINTS: "http://minio.minio.svc.cluster.local:9000"