apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mail-relay
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/SanchesWise/Kryukov_youtube'
    path: gitlab/postfix/manifests
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mail-relay
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
