users:
  - name: kubernetes-admin
    user:
      client-certificate-data: DATA+OMITTED
      client-key-data: DATA+OMITTED
clusters:
  - cluster:
      certificate-authority-data: DATA+OMITTED
      server: https://10.10.2.110:7443
    name: cluster.local
contexts: []
apiVersion: v1
kind: Config
preferences: {}
current-context: kubernetes-admin@cluster.local
