apiVersion: v1
kind: Namespace
metadata:
  name: velero-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-logs
  namespace: velero-test
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: velero-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      # 👇 ВАЖНО: Эта аннотация включает Restic/Kopia для тома "logs"
      annotations:
        backup.velero.io/backup-volumes: logs
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - mountPath: /var/log/nginx
          name: logs
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: nginx-logs