imagePullPolicy: IfNotPresent
revisionHistoryLimit: 3
gitlabUrl: https://gitlab.ccsfarm.local/

# Лимит одновременно запущенных задач
concurrent: 5
checkInterval: 30
logLevel: info
logFormat: json

# 1. Доверие корневому сертификату для менеджера (основной под)
certsSecretName: custom-ca-certs
envVars:
  - name: SSL_CERT_FILE
    value: /home/gitlab-runner/.gitlab-runner/certs/ccsfarm-ca.crt

rbac:
  create: true
  rules:
  - resources: ["pods", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
  - apiGroups: [""]
    resources: ["pods/exec", "pods/attach"]
    verbs: ["create", "patch", "delete"]

metrics:
  enabled: true
  portName: metrics
  port: 9252
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: kube-prometheus-stack
    interval: "30s"      

runners:
  # Секрет с ключами доступа к MinIO (accesskey/secretkey)
  secret: dev-gitlab-runner
  config: |
    [[runners]]
      output_limit = 10000
      [runners.kubernetes]
        image = "registry.red-soft.ru/ubi8/ubi-micro"
        dns_config_options = ["ndots:2"]
        cpu_limit = "4"
        memory_limit = "12Gi"
        cpu_request = "1"
        memory_request = "8Gi"
        image_pull_secrets = ["regcred"]        
        
        # 2. Проброс DNS имен (Host Aliases)
        [[runners.kubernetes.host_aliases]]
          ip = "10.10.2.111"
          hostnames = ["gitlab.ccsfarm.local", "registry-docker.ccsfarm.local"]
        [[runners.kubernetes.host_aliases]]
          ip = "10.10.2.122"
          hostnames = ["minio-ext-fast.ccsfarm.local"]

        # 3. Доверие корневому сертификату для исполнитей (Jobs)
        [[runners.kubernetes.volumes.secret]]
          name = "custom-ca-certs"
          mount_path = "/etc/ssl/certs/ccsfarm-ca.crt"
          sub_path = "ccsfarm-ca.crt"
          read_only = true 
        
        environment = [
          "SSL_CERT_FILE=/etc/ssl/certs/ccsfarm-ca.crt"
        ]

      # 4. Настройка кэширования на внешний MinIO
      [runners.cache]
        Type = "s3"
        Path = ""
        Shared = true
        [runners.cache.s3]
          ServerAddress = "minio-ext-fast.ccsfarm.local:9000"
          BucketName = "dev-runner-cache"
          BucketLocation = "us-east-1"
          Insecure = true
          AuthenticationType = "access-key"

securityContext:
  runAsUser: 100
  fsGroup: 65533

resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 100m