apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cert-manager # Namespace где стоит сам cert-manager
  selector:
    matchLabels:
      app: cert-manager
      app.kubernetes.io/component: controller
  endpoints:
  - port: tcp-prometheus-servicemonitor # Обычно этот порт открыт на сервисе cert-manager
    interval: 60s
    path: /metrics