# Секрет с доступами к БД
apiVersion: v1
kind: Secret
metadata:
  name: db-exporter-secrets
  namespace: monitoring
type: Opaque
stringData:
  # Подключение к Redis (имя сервиса:порт)
  redis-addr: "redis.redis.svc.cluster.local:6379"
  redis-password: "password123" 
  
  # Подключение к Postgres
  # Формат: postgresql://user:password@host:port/dbname?sslmode=disable
  postgres-conn: "host=postgres-np.postgres.svc.cluster.local port=5432 user=gitlab password=FeerDe3o dbname=gitlab sslmode=disable"

---
# -------------------
# 1. REDIS EXPORTER
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.55.0
        env:
        - name: REDIS_ADDR
          valueFrom: { secretKeyRef: { name: db-exporter-secrets, key: redis-addr } }
        - name: REDIS_PASSWORD
          valueFrom: { secretKeyRef: { name: db-exporter-secrets, key: redis-password } }
        ports:
        - containerPort: 9121
          name: metrics

---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    app: redis-exporter # Метка для ServiceMonitor
spec:
  ports:
  - port: 9121
    targetPort: 9121
    name: metrics
  selector:
    app: redis-exporter

---
# Инструкция для Prometheus: "Считывай метрики отсюда"
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack # ОБЯЗАТЕЛЬНО: чтобы Prometheus увидел этот монитор
spec:
  selector:
    matchLabels:
      app: redis-exporter
  endpoints:
  - port: metrics
    interval: 30s

---
# -------------------
# 2. POSTGRES EXPORTER
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:v0.15.0
        env:
        - name: DATA_SOURCE_NAME
          valueFrom: { secretKeyRef: { name: db-exporter-secrets, key: postgres-conn } }
        ports:
        - containerPort: 9187
          name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    app: postgres-exporter
spec:
  ports:
  - port: 9187
    targetPort: 9187
    name: metrics
  selector:
    app: postgres-exporter

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
  - port: metrics
    interval: 30s