apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: webservice # Стандартный лейбл GitLab
  namespaceSelector:
    matchNames:
      - gitlab
  endpoints:
  # 1. Основные метрики GitLab (Rails/Unicorn/Puma)
  - port: http-metrics-ws
    path: /metrics
    interval: 30s
    scheme: http
  
  # # 2. Метрики Workhorse (обработка git-запросов)
  # - port: http-workhorse
  #   path: /metrics
  #   interval: 30s
  #   scheme: http
---  
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-gitaly
  namespace: gitlab
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: gitaly
      release: gitlab
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-exporter
  namespace: gitlab
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: gitlab-exporter
      release: gitlab
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-kas
  namespace: gitlab
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: kas
      release: gitlab
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-sidekiq
  namespace: gitlab
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: sidekiq
      release: gitlab
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
      scheme: http