apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry
---
# ==========================================================
# 1. SECRETS (Пароли и ключи)
# ==========================================================
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds
  namespace: docker-registry
type: Opaque
stringData:
  s3-access-key: "admin"      
  s3-secret-key: "password"   
  
  # htpasswd: admin / password
  htpasswd: |
    admin:$2y$05$ncdNAqY15kNLfOanZiMrausiz42PszOJTfZyT.1hflOfWnYnSlcxO

---
# ==========================================================
# 2. DOCKER REGISTRY (Backend + Metrics)
# ==========================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: registry
        image: registry:2.8
        ports:
        - containerPort: 5000
          name: registry
        - containerPort: 5001   # <--- НОВОЕ: Порт для метрик
          name: debug
        env:
        # === ВКЛЮЧЕНИЕ МЕТРИК PROMETHEUS ===
        - name: REGISTRY_HTTP_DEBUG_ADDR
          value: ":5001"
        - name: REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED
          value: "true"

        # === НАСТРОЙКИ ХРАНИЛИЩА (S3) ===
        - name: REGISTRY_STORAGE
          value: "s3"
        - name: REGISTRY_STORAGE_S3_REGION
          value: "us-east-1"
        - name: REGISTRY_STORAGE_S3_FORCEPATHSTYLE
          value: "true"          
        - name: REGISTRY_STORAGE_S3_BUCKET
          value: "docker-registry"
        - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
          value: "http://minio.minio.svc.cluster.local:9000"
        - name: REGISTRY_STORAGE_S3_SECURE
          value: "false"
        - name: REGISTRY_STORAGE_S3_V4AUTH
          value: "true"
        - name: REGISTRY_STORAGE_S3_CHUNKSIZE
          value: "5242880"
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        
        # Ключи
        - name: REGISTRY_STORAGE_S3_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: registry-creds
              key: s3-access-key
        - name: REGISTRY_STORAGE_S3_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: registry-creds
              key: s3-secret-key
        
        # === НАСТРОЙКИ АВТОРИЗАЦИИ ===
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
        
        # === НАСТРОЙКИ CORS ===
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin
          value: "['https://registry-ui.ccsfarm.local']"
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials
          value: "['true']"
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods
          value: "['HEAD', 'GET', 'OPTIONS', 'DELETE']"
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers
          value: "['Authorization', 'Accept', 'Cache-Control']"
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers
          value: "['Docker-Content-Digest']"

        volumeMounts:
        - name: auth-vol
          mountPath: /auth
      volumes:
      - name: auth-vol
        secret:
          secretName: registry-creds
          items:
          - key: htpasswd
            path: htpasswd
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-svc
  namespace: docker-registry
  labels:
    app: docker-registry  # Важно для ServiceMonitor
spec:
  selector:
    app: docker-registry
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
    - name: debug       # <--- НОВОЕ: Открываем порт метрик в сервисе
      port: 5001
      targetPort: 5001
---
# ==========================================================
# 3. SERVICE MONITOR (Для Prometheus Stack)
# ==========================================================
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: docker-registry-monitor
  namespace: docker-registry
  labels:
    # Этот лейбл критичен, чтобы Prometheus Operator нашел этот монитор
    # Если у вас release называется по-другому, поменяйте значение
    release: kube-prometheus-stack 
spec:
  selector:
    matchLabels:
      app: docker-registry
  namespaceSelector:
    matchNames:
      - docker-registry
  endpoints:
  - port: debug
    path: /metrics
    interval: 30s
---
# ==========================================================
# 4. REGISTRY UI (Frontend)
# ==========================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
      - name: ui
        image: joxit/docker-registry-ui:2.5
        ports:
        - containerPort: 80
        env:
        - name: REGISTRY_URL
          value: https://registry-docker.ccsfarm.local
        - name: REGISTRY_TITLE
          value: "Registry"
        - name: SINGLE_REGISTRY
          value: "true"
        - name: DELETE_IMAGES
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui-svc
  namespace: docker-registry
spec:
  selector:
    app: registry-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
---
# ==========================================================
# 5. INGRESS (Маршрутизация)
# ==========================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: docker-registry
  annotations:
    cert-manager.io/cluster-issuer: ccsfarm-ca-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - registry-docker.ccsfarm.local
        - registry-ui.ccsfarm.local
      secretName: registry-tls-secret
  rules:
    - host: registry-docker.ccsfarm.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docker-registry-svc
                port:
                  number: 5000
    - host: registry-ui.ccsfarm.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry-ui-svc
                port:
                  number: 80