apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: prod  # Укажите нужный namespace!
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS1kb2NrZXIuY2NzZmFybS5sb2NhbCI6IHsKICAgICAgImF1dGgiOiAiWVdSdGFXNDZjR0Z6YzNkdmNtUT0iCiAgICB9CiAgfQp9Cg==
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: dev  # Укажите нужный namespace!
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS1kb2NrZXIuY2NzZmFybS5sb2NhbCI6IHsKICAgICAgImF1dGgiOiAiWVdSdGFXNDZjR0Z6YzNkdmNtUT0iCiAgICB9CiAgfQp9Cg==
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: postgres  # Укажите нужный namespace!
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS1kb2NrZXIuY2NzZmFybS5sb2NhbCI6IHsKICAgICAgImF1dGgiOiAiWVdSdGFXNDZjR0Z6YzNkdmNtUT0iCiAgICB9CiAgfQp9Cg==