apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: gitlab
  labels:
    manual: "yes"
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: us-east-1
    host: minio-ext-fast.ccsfarm.local
    endpoint: http://minio-ext-fast.ccsfarm.local:9000
    path_style: true
    aws_access_key_id: gitlab 
    aws_secret_access_key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: gitlab
  labels:
    manual: "yes"
type: Opaque
stringData:
  config: |
    s3:
      bucket: gitlab-registry-storage
      accesskey: gitlab
      secretkey: password
      region: us-east-1
      regionendpoint: "http://minio-ext-fast.ccsfarm.local:9000"
      v4auth: true