{{- with .Values.objectStore }}
{{- if .legacyAudience }}
  {{- fail ".objectStore.legacyAudience is deprecated, please make sure you use latest AIStor version and remove this value" }}
{{- end }}
{{- with .features }}
  {{- if .bucketDNS }}
  {{- fail ".objectStore.features.bucketDNS is deprecated, please set the env variable MINIO_DOMAIN instead." }}
  {{- end }}
  {{- if .domains }}
  {{- fail ".objectStore.features.domains is deprecated, please set the env variable MINIO_BROWSER_REDIRECT_URL instead." }}
  {{- end }}
  {{- if .enableSFTP }}
  {{- fail ".objectStore.features.enableSFTP is deprecated, please set objectStore.sftp instead." }}
  {{- end }}
{{- end }}
apiVersion: aistor.min.io/v1
kind: ObjectStore
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespaceOverride | default $.Release.Namespace | quote }}
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
    {{- if $.Values.labels }}
    {{ $.Values.labels | toYaml | nindent 4 }}
    {{- end }}
  {{- $metricsEnabled := dig "metrics" "enabled" false . }}
  {{- $annotations := $.Values.annotations }}
  {{- if or $metricsEnabled $annotations }}
  annotations:
    {{- if $annotations }}
    {{ $annotations | toYaml | nindent 4 }}
    {{- end }}
    {{- if $metricsEnabled }}
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: {{ dig "metrics" "port" 9000 . | quote }}
    prometheus.io/scrape: "true"
    prometheus.io/scheme: {{ dig "metrics" "protocol" "http" . | quote }}
    {{- end }}
  {{- end }}
{{- if dig "scheduler" "name" "" . }}
scheduler:
  name: {{ dig "scheduler" "name" "" . }}
{{- end }}
spec:
  {{- if .image }}
  {{- $repository := .image.repository }}
  {{- $tag := .image.digest | default .image.tag }}
  {{- if or (and $repository (not $tag)) (and (not $repository) $tag) }}
  {{- fail "Both repository and tag / digest must be set" }}
  {{- end }}
  {{- if (and $repository $tag) }}
  image: "{{ $repository }}:{{ $tag }}"
  {{- end }}
  imagePullPolicy: {{ dig "image" "pullPolicy" "IfNotPresent" . }}
  {{- end }}
  {{- if dig "imagePullSecret" "name" "" . }}
  imagePullSecret:
    name: {{ dig "imagePullSecret" "name" "" . }}
  {{- end }}
  ## Secret with default environment variable configurations
  configuration:
    name: {{ .configuration.name }}
  pools:
    {{- range (dig "pools" (list) .) }}
    - servers: {{ dig "servers" 4 . }}
      {{ with (dig "name" "" .) }}
      name: {{ . }}
      {{- end }}
      volumesPerServer: {{ dig "volumesPerServer" 4 . }}
      {{- if dig "runtimeClassName" "" . }}
      runtimeClassName: {{ dig "runtimeClassName" "" . }}
      {{- end }}
      volumeClaimTemplate:
        metadata:
        {{- if ne .storageNamePrefix "" }}
          name: {{ .storageNamePrefix | default "data" | quote }}
        {{- end }}
        {{- with (dig "storageAnnotations" (dict) .) }}
          annotations: {{- toYaml . | nindent 12 }}
        {{- end }}
        spec:
          {{- if dig "storageClassName" "" . }}
          storageClassName: {{ dig "storageClassName" "" . }}
          {{- end }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ dig "size" "10Gi" . }}
      {{- with (dig "annotations" (dict) .) }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "labels" (dict) .) }}
      labels: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "tolerations" (list) .) }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "nodeSelector" (dict) .) }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "affinity" (dict) .) }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "resources" (dict) .) }}
      resources: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if hasKey . "securityContext" }}
      securityContext: {{- if eq (len .securityContext) 0 }} {} {{- end }}
      {{- with (dig "securityContext" (dict) .) }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if hasKey . "containerSecurityContext" }}
      containerSecurityContext: {{- if eq (len .containerSecurityContext) 0 }} {} {{- end }}
      {{- with (dig "containerSecurityContext" (dict) .) }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with (dig "topologySpreadConstraints" (list) .) }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if hasKey . "spreadZoneConfig" }}
      spreadZoneConfig: {{- if eq (len .spreadZoneConfig) 0 }} { } {{- end }}
      {{- with (dig "spreadZoneConfig" (dict) .) }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
    {{- end }}
  mountPath: {{ dig "mountPath" "/export" . | quote }}
  {{- with .subPath }}
  subPath: {{ . | quote }}
  {{- end }}
  {{- if dig "certificates" "" . }}
  certificates:
    disableAutoCert: {{ dig "certificates" "disableAutoCert" false . }}
    {{- if ((.certificates).certExpiryAlertThreshold) }}
    certExpiryAlertThreshold: {{ ((.certificates).certExpiryAlertThreshold) }}
    {{- end }}
    {{- with (dig "certificates" "config" (dict) .) }}
    config: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "certificates" "trustedCAs" (list) .) }}
    trustedCAs: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "certificates" "server" (list) .) }}
    server: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "certificates" "KESClient" (list) .) }}
    KESClient: {{ ((.certificates).KESClient) }}
    {{- end }}
    {{- with (dig "certificates" "client" (dict) .) }}
    client: {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- with (dig "sftp" (dict) .) }}
  sftp: {{- toYaml . | nindent 4 }}
  {{- end }}
  podManagementPolicy: {{ dig "podManagementPolicy" "Parallel" . }}
  {{- if dig "rollingTimeoutSeconds" "" . }}
  rollingTimeoutSeconds: {{ dig "rollingTimeoutSeconds" "" . }}
  {{- end }}
  {{- with (dig "readiness" (dict) .) }}
  readiness: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "liveness" (dict) .) }}
  liveness: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "startup" (dict) .) }}
  startup: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "lifecycle" (dict) .) }}
  lifecycle: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "services" (dict) .) }}
  services: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if dig "serviceAccountName" "" . }}
  serviceAccountName: {{ dig "serviceAccountName" "" . }}
  {{- end }}
  prometheusOperator: {{ dig "prometheusOperator" "false" . }}
  {{- with (dig "logging" (dict) .) }}
  logging: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "env" (list) .) }}
  env: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if dig "priorityClassName" "" . }}
  priorityClassName: {{ dig "priorityClassName" "" . }}
  {{- end }}
  {{- with (dig "initContainers" (list) .) }}
  initContainers: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "sideCars" (dict) .) }}
  sideCars: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "additionalVolumes" (list) .) }}
  additionalVolumes: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "additionalVolumeMounts" (list) .) }}
  additionalVolumeMounts: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if dig "kes" "configuration" false . }}
  kes:
    {{- if .kes.image }}
    {{-  $kesRepository := .kes.image.repository }}
    {{- $kesTag := .kes.image.digest | default .kes.image.tag }}
    {{- if or (and $kesRepository (not $kesTag)) (and (not $kesRepository) $kesTag) }}
    {{- fail "Both repository and tag / digest must be set" }}
    {{- end }}
    {{- if (and $kesRepository $kesTag) }}
    image: "{{ $kesRepository }}:{{ $kesTag }}"
    {{- end }}
    {{- end }}
    {{- with (dig "kes" "env" (list) .) }}
    env: {{- toYaml . | nindent 4 }}
    {{- end }}
    replicas: {{ .kes.replicas | int }}
    kesSecret:
      name: "kes-configuration"
    imagePullPolicy: {{ .kes.imagePullPolicy | quote }}
    {{- with (dig "kes" "externalCertSecret" (dict) .) }}
    externalCertSecret: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "kes" "clientCertSecret" (dict) .) }}
    clientCertSecret: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "kes" "trustedCAs" (dict) .) }}
    trustedCAs: {{- toYaml . | nindent 6 }}
    {{- end }}
    ## Key name to be created on the KMS, default is "my-minio-key"
    keyName: {{ .kes.keyName | quote }}
    {{- with (dig "resources" (dict) .) }}
    resources: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "nodeSelector" (dict) .) }}
    nodeSelector: {{- toYaml . | nindent 6 }}
    {{- end }}
    affinity:
      nodeAffinity: {}
      podAffinity: {}
      podAntiAffinity: {}
    tolerations: []
    {{- with (dig "annotations" (dict) .) }}
    annotations: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "labels" (dict) .) }}
    labels: {{- toYaml . | nindent 6 }}
    {{- end }}
    serviceAccountName: {{ .kes.serviceAccountName | quote }}
    {{- if hasKey .kes "securityContext" }}
    securityContext: {{- if eq (len .kes.securityContext) 0 }} {} {{- end }}
    {{- with (dig "kes" "securityContext" (dict) .) }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- if hasKey .kes "containerSecurityContext" }}
    containerSecurityContext: {{- if eq (len .kes.containerSecurityContext) 0 }} { } {{- end }}
      {{- with (dig "kes" "containerSecurityContext" (dict) .) }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
