---
apiVersion: v1
kind: Namespace
metadata:
  name: frigate
---
# Конфигурация Frigate
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: frigate
data:
  config.yml: |
    mqtt:
      enabled: false
    
    detectors:
      cpu:
        type: cpu
        num_threads: 2
    
    cameras:
      test_camera_1:
        enabled: true
        ffmpeg:
          inputs:
            - path: rtsp://admin:12345@91.210.159.231:7011/Streaming/Channels/1?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - record
        detect:
          enabled: true
          width: 1280
          height: 720
        record:
          enabled: true
          retain:
            days: 7
            mode: motion
        snapshots:
          enabled: true
          retain:
            default: 10
        objects:
          track:
            - person
            - car
          filters:
            person:
              min_area: 5000
              max_area: 100000
              threshold: 0.8
    
    # Настройки записи
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
    
    # Настройки для работы без GPU
    ffmpeg:
      hwaccel_args: []
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
---
# PVC для хранения видеоархива
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-storage
  namespace: frigate
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 100Gi
---
# Deployment Frigate
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
  labels:
    app: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
      - name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: web
        - containerPort: 1935
          name: rtmp
        - containerPort: 8554
          name: rtsp
        - containerPort: 8555
          name: webrtc
        env:
        - name: FRIGATE_PORT
          value: "5000"
        - name: FRIGATE_HOST
          value: "0.0.0.0" 
        - name: FRIGATE_RTSP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: frigate-secrets
              key: rtsp-password
        - name: CONFIG_FILE
          value: "/config/config.yml"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: storage
          mountPath: /media/frigate
        - name: tmp-cache
          mountPath: /tmp/cache
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5        
      volumes:
      - name: config
        configMap:
          name: frigate-config
      - name: storage
        persistentVolumeClaim:
          claimName: frigate-storage
      - name: tmp-cache
        emptyDir:
          sizeLimit: "1Gi"
---
# Secrets для Frigate
apiVersion: v1
kind: Secret
metadata:
  name: frigate-secrets
  namespace: frigate
type: Opaque
data:
  rtsp-password: cGFzc3dvcmQ=  # password в base64
---
# Service для доступа к веб-интерфейсу
apiVersion: v1
kind: Service
metadata:
  name: frigate-service
  namespace: frigate
spec:
  selector:
    app: frigate
  ports:
  - name: web
    port: 5000
    targetPort: 5000
    nodePort: 30080
  - name: rtmp
    port: 1935
    targetPort: 1935
    nodePort: 31935
  - name: rtsp
    port: 8554
    targetPort: 8554
    nodePort: 30554
  type: NodePort
---
# Ingress для веб-интерфейса
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate-ingress
  namespace: frigate
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers: "4 256k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: frigate.ccsfarm.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frigate-service
            port:
              number: 5000