image:
  repository: nvcr.io/nvidia/k8s/dcgm-exporter
  tag: "3.2.5-3.1.8-ubi8"

runtimeClassName: nvidia

# Включаем привилегированный режим
privileged: true

# Дополнительные настройки безопасности для RedOS/SELinux
securityContext:
  privileged: true
  capabilities:
    add:
      - SYS_ADMIN
      - SETFCAP
  # Отключаем ограничения SELinux (запуск в контексте SPC)
  seLinuxOptions:
    type: "spc_t"

extraConfig:
  user: "0"

env:
  - name: NVIDIA_VISIBLE_DEVICES
    value: "all"
  - name: NVIDIA_DRIVER_CAPABILITIES
    value: "all" # Разрешаем все возможности драйвера
  - name: LD_LIBRARY_PATH
    value: "/usr/lib64:/usr/local/nvidia/lib64"

nodeSelector:
  nvidia.com/gpu.present: "true"

tolerations:
  - operator: "Exists"

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
  interval: 15s