apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utils
  source:
    repoURL: https://helm.min.io/
    targetRevision: 5.4.0
    chart: minio
    helm:
      parameters:
        - name: consoleIngress.enabled
          value: 'true'
        - name: consoleIngress.hosts[0]
          value: minio.ccsfarm.local
        - name: consoleIngress.ingressClassName
          value: nginx
        - name: consoleService.type
          value: NodePort
        - name: image.tag
          value: RELEASE.2023-11-01T01-57-10Z-cpuv1
        - name: mcImage.tag
          value: RELEASE.2023-11-01T01-57-10Z-cpuv1
        - name: replicas
          value: '3'
        - name: resources.requests.memory
          value: 512Mi
        - name: persistence.size
          value: 20Gi
        - name: persistence.storageClass
          value: managed-nfs-storage
        - name: rootPassword
          value: password
        - name: rootUser
          value: admin
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true