apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: redis
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utils
  source:
    repoURL: 'https://charts.pascaliske.dev'
    chart: pascaliske/redis
    targetRevision: 2.1.0
    helm:
      parameters:
        - name: global.storageClass
          value: managed-nfs-storage
        - name: global.redis.password
          value: 'qUwTt8g9it'
        - name: master.persistence.storageClass
          value: managed-nfs-storage
        - name: pdb.create
          value: 'true'
        - name: replica.persistence.storageClass
          value: managed-nfs-storage
        - name: replica.replicaCount
          value: '1'
#        - name: master.resources.requests.memory
#          value: "256Mi"
#        - name: master.resources.requests.cpu
#          value: "0.5"
#        - name: master.resources.limits.memory
#          value: "256Mi"
#        - name: master.resources.limits.cpu
#          value: "0.5"
#        - name: replica.resources.requests.memory
#          value: "256Mi"
#        - name: replica.resources.requests.cpu
#          value: "0.5"
#        - name: replica.resources.limits.memory
#          value: "256Mi"
#        - name: replica.resources.limits.cpu
#          value: "0.5"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
